### ISSUE TITLE
Preview application out of sync

### ISSUE THREAD

**Issue by lukemorton** [madetech/site#116]
It seems the preview application hasn’t been kept up to date with the content type changes we’ve been making. As such the preview application currently has rendering errors.

![](https://www.dropbox.com/s/ko6f3qdam1yglzd/Screenshot%202019-12-21%2014.41.16.png?raw=1)

https://madetech-site-preview.herokuapp.com/?id=7pqbBbEaY66C0MOJacv1a7

**How does preview work for a content editor?**

You can access the preview application from a link within the Contentful admin. Go to any page in the Contentful admin, then look for a button on the right hand side that says “Open preview”. This will then open the preview for that page.

**How do we keep preview application in line with content type changes?**

If you look at the codebase, there is a directory called `preview/`, in there you will find a README showing you how to run the preview app in development mode on your laptop. You can then edit the `preview/src/data/contentful.js` to fix the issues with the data model. The preview app pulls live from Contentful unlike the main Gatsby application and uses this code to do so. This means that if you have new fields that needs special treatment in content types you need to account for them in this file as.

WARNING: Please be aware if you’ve added any NPM modules and haven’t also added them to the preview applications separate `package.json` you might also find issues there.

**Comment by NinammaMT** [comment]
Thanks for pointing this out, Luke! 
We didn't understand the preview site very well and it wasn't ideal that we just let it be. 😬

This has now been fixed, so the preview app should be looking as snazzy as the main site! 🎉
